name: Docker Images Builder

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

env:
  DOCKERHUB_USER: ${{ github.repository_owner }}
  GITHUB_USER: ${{ github.repository_owner }}
  QUAY_USER: ${{ github.repository_owner }}
  
  IMAGE_BASE_NAME: alpine-android-base
  IMAGE_NAME: alpine-android
  
  DEFAULT_JDK_VERSION: 17
  LATEST_STABLE_API: 35

jobs:
  build_base_images:
    name: Build Alpine Android Base Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        shell: sh
        run: |
          set -eu

          case ${{ matrix.jdk }} in
              8)
                CMDLINE_VERSION="8.0"
                SDK_TOOLS_VERSION="9123335" ;;
              11)
                CMDLINE_VERSION="10.0"
                SDK_TOOLS_VERSION="9862592" ;;
              *)
                CMDLINE_VERSION="19.0"
                SDK_TOOLS_VERSION="13114758" ;;
          esac
          echo "CMDLINE_VERSION=${CMDLINE_VERSION}" >> $GITHUB_ENV
          echo "SDK_TOOLS_VERSION=${SDK_TOOLS_VERSION}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_BASE_NAME }}
            # ghcr.io/${{ env.GITHUB_USER }}/${{ env.IMAGE_BASE_NAME }}
            # quay.io/${{ env.QUAY_USER }}/${{ env.IMAGE_BASE_NAME }}
          tags: |
            type=raw,value=jdk${{ matrix.jdk }}
            type=raw,value=latest-jdk${{ matrix.jdk }}
            type=raw,value=latest,enable=${{ matrix.jdk == env.DEFAULT_JDK_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ env.GITHUB_USER }}
#           password: ${{ secrets.GITHUB_PASS }}

#       - name: Login to Quay
#         uses: docker/login-action@v3
#         with:
#           registry: quay.io
#           username: ${{ env.QUAY_USER }}
#           password: ${{ secrets.QUAY_PASS }}

      - name: Build Android Base JDK${{ matrix.jdk }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/base.Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            JDK_VERSION=${{ matrix.jdk }}
            CMDLINE_VERSION=${{ env.CMDLINE_VERSION }}
            SDK_TOOLS_VERSION=${{ env.SDK_TOOLS_VERSION }}
